In [1]:
import math
import cmath
import numpy as np
from numpy import linalg

In [4]:
U1 = 3
U2 = 4
R1 = 10
R2 = 13
L1 = 0.22
L2 = 0.07
C1 = 0.00023
C2 = 0.000085
f = 75

In [8]:
w = 2*math.pi*f
w

471.23889803846896

In [10]:
ZL1 = complex(0,w*L1)
ZL1

103.67255756846318j

In [12]:
ZL2 = complex(0,w*L2)
ZL2

32.98672286269283j

In [15]:
ZC1 = -(complex(0,1)/(w*C1))
ZC1

(-0-9.226373512573643j)

In [16]:
ZC2 = -(complex(0,1)/(w*C2))
ZC2

(-0-24.965481269316918j)

In [17]:
M = np.array([[R2+R1+ZC1+ZL1,-ZC1-R1,-R2],[-R1-ZC1,ZC1+R1+ZL2,-ZL2],[-R2,-ZL2,ZL2+R2+ZC2]])
M

array([[ 23.+94.44618406j, -10. +9.22637351j, -13. +0.j        ],
       [-10. +9.22637351j,  10.+23.76034935j,  -0.-32.98672286j],
       [-13. +0.j        ,  -0.-32.98672286j,  13. +8.02124159j]])

In [20]:
Minv = linalg.inv(M)
Minv

array([[0.00124782-0.01105699j, 0.003308  -0.00297538j,
        0.00518173-0.00586036j],
       [0.003308  -0.00297538j, 0.01542931+0.00262558j,
        0.01373693+0.02769962j],
       [0.00518173-0.00586036j, 0.01373693+0.02769962j,
        0.02151782+0.01571938j]])

In [21]:
P = np.dot(Minv, np.array([[0],[3],[-4]]))
P

array([[-0.0108029 +0.01451527j],
       [-0.00865979-0.10292173j],
       [-0.04486051+0.02022134j]])

In [24]:
IA = P[0][0]
IA

(-0.010802900391850175+0.01451527401801071j)

In [25]:
IB = P[1][0]
IB

(-0.008659790520641808-0.10292173483319066j)

In [26]:
IC = P[2][0]
IC

(-0.044860513630751414+0.020221343855072654j)

In [29]:
UL2 = abs(ZL2 * (IB - IC))
UL2

4.233972797701627

In [32]:
#I got these values out of:ZL2 * (IB - IC)
phi =  math.atan(1.1941432206622653/4.062086609148517)
phi

0.28591817765805744

In [33]:
math.degrees(phi)

16.381904865878358